### ISSUE TITLE
the websocket output should break line when the message is too long in one line

### ISSUE THREAD

**Issue by iflamed** [tomlerendu/Websocket-King#1]
![image](https://user-images.githubusercontent.com/1819687/100052552-2012c480-2e59-11eb-907f-41758c461872.png)

the output window is scrollable with left-right.

**Comment by tomlerendu** [comment]
Thanks for reporting this issue. It will be resolved in the next release.

**Comment by tomlerendu** [comment]
Fixed in 3.0.1
