### ISSUE TITLE
[Question] Looking for the "Save As" button

### ISSUE THREAD

**Issue by jetchoong-dev** [tomlerendu/Websocket-King#3]
I am seeing following message on the left panel, 

"NO SAVED PAYLOADS
Use "Save As" to store payloads for reuse."

The problem is I don't find a "Save As" button anywhere in the application, I am not completely sure the Save As feature is ready or is in dev, I don't see existing or closed issue regarding this as well. Tried creating new project in the left panel, don't find the Save button too. I am using Chrome Version 87.0.4280.88 (Official Build) (64-bit).

**Comment by tomlerendu** [comment]
Hi @jetstudio, the save as button appears after content is entered into a connection like so:
![image](https://user-images.githubusercontent.com/3859851/103072368-50b35e80-45bd-11eb-8b6b-7b6f3a0fe9b8.png)
