### ISSUE TITLE
Payload editor cursor jumps to End after typing a character

### ISSUE THREAD

**Issue by justgus60** [tomlerendu/Websocket-King#4]
**Describe the bug**
When typing in the payload editor, after every key the cursor jumps to the end of the payload. Editing a saved payload in the popup works normally.
I usually use the Chrome extension, I have also tried this using websocketking.com with Firefox and it has the same issue.

https://user-images.githubusercontent.com/77354565/104355926-f5480280-54d0-11eb-9459-07f089f1edb3.MP4

**Desktop (please complete the following information):**
 - OS: Win7
 - Browser Chrome
 - Version 87.0.4280.141

**Comment by tomlerendu** [comment]
Thanks @justgus60, a fix has been deployed for this.
